### ISSUE TITLE
phonegap build

### ISSUE THREAD

**Issue by honght0068** [kristianhristov/cordova-cookie-master#4]
Found that the ios build is okay for phonegap build but not for android.
Any directory named wrongly?

Error - Plugin error (you probably need to remove plugin files from your app): Error during processing of action! Attempting to revert... Failed to install 'com.cordova.plugins.cookiemaster':Error: Uh oh! "/tmp/gimlet/5755/1630540/www_android/project/cordova/plugins/com.cordova.plugins.cookiemaster/src/android/com/cordova/plugins/cookiemaster/CookieMaster.java" not found! at Object.module.exports.common.copyFile (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/platforms/common.js:38:40) at Object.module.exports.common.copyNewFile (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/platforms/common.js:69:16) at Object.module.exports.source-file.install (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/platforms/android.js:78:20) at installWrapper (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/platforms/platforms.js:76:32) at Object.ActionStack.process (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25) at handleInstall (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/install.js:543:20) at /home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/install.js:340:24 at _fulfilled (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:749:13) Uh oh! "/tmp/gimlet/5755/1630540/www_android/project/cordova/plugins/com.cordova.plugins.cookiemaster/src/android/com/cordova/plugins/cookiemaster/CookieMaster.java" not found! - You can fix this here

**Comment by kristianhristov** [comment]
I haven't tested with Phonegap Build so I can't really say what the problem is. The plugin works well if you use the <code>cordova plugin add</code> command.

**Comment by honght0068** [comment]
Hi,

Cordova plugin moved to npm. Could you upload this to Cordova npm?
http://plugins.cordova.io/npm/index.html
